const Icons = {
  Dashboard: <span className="material-symbols-outlined">dashboard</span>,
  List: <span className="material-symbols-outlined">lists</span>,
  Close: <span className="material-symbols-outlined">close</span>,
  Setting: <span className="material-symbols-outlined">settings</span>,
  LoginIcon: <span className="material-symbols-outlined">login</span>,
  LogoutIcon: <span className="material-symbols-outlined">logout</span>,
  Power: <span className="material-symbols-outlined">power_settings_new</span>,
  Check: <span className="material-symbols-outlined">check</span>,
  Add: <span className="material-symbols-outlined">add</span>,
  Delete: <span className="material-symbols-outlined">delete</span>,
  Edit: <span className="material-symbols-outlined">edit_square</span>,
  View: <span className="material-symbols-outlined">visibility</span>,
  ViewOff: <span className="material-symbols-outlined">visibility_off</span>,
  Error: <span className="material-symbols-outlined">error</span>,
  Filter: (
    <span className="material-symbols-outlined material-fill">filter_alt</span>
  ),
  Random: <span className="material-symbols-outlined">shuffle</span>,
  AvatarIcon: <span className="material-symbols-outlined">account_circle</span>,
};

export const {
  Dashboard,
  List,
  Close,
  Setting,
  LoginIcon,
  LogoutIcon,
  Power,
  Check,
  Add,
  Delete,
  Edit,
  View,
  ViewOff,
  Error,
  Filter,
  Random,
  AvatarIcon,
} = Icons;
